-- 1. Create the images table
CREATE TABLE images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  url TEXT NOT NULL,
  category TEXT NOT NULL
);

-- 2. Set up Storage
-- Go to Storage in the Supabase dashboard and create a new bucket called 'gallery'.
-- Make sure to set it to 'Public'.

-- 3. (Optional) Enable Row Level Security (RLS)
-- For a simple portfolio, you can keep it disabled if you just want it to work.
-- If you want it secure, you can add policies later.
